#! /usr/bin/env bash
set -e # exit entire script when command exits with non-zero status
# Install dependencies
npm install
# Publish `production` release
expo publish --release-channel production --non-interactive
# Start building standalone android build using `production` release channel
expo build:ios --release-channel production --non-interactive --no-publish
# Download the artifact to current directory as `app.ipa`
curl -o app.ipa "$(expo url:ipa --non-interactive)"
#### 7. Submit standalone iOS app to iTunes Connect ####
# Make sure the following env variables are set
# export DELIVER_USERNAME=<your-itunes-connect-email>
# export DELIVER_PASSWORD=<your-itunes-connect-password>
# Use fastlane to upload your current standalone iOS build to test flight on iTunes Connect.
fastlane deliver --verbose --ipa "app.ipa" --skip_screenshots --skip_metadata